[tool.black]
line-length = 160
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | \.history
  | \.local
  | buck-out
  | build
  | dist
  | migrations
  | venv
)/
'''

[tool.flake8]
ignore = "E712, E203, E266, E501, W503, W504, F403, F841"
max-line-length = 160
select = "B,C,E,F,W,T4,B9"
exclude = [
  "*/migrations/*",
  "./migrations*",
  "./venv*",
  ".svn",
  "CVS",
  ".bzr",
  ".hg",
  ".git",
  "__pycache__",
]

[tool.isort]
profile = "black"
skip = ["migrations", ".env", "venv", ".local", ".history", ".vscode"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-p no:warnings"

[tool.pytest.ini_options.markers]
integration = "marks tests as integration (deselect with '-m \"not integration\"')"
