[tool.black]
line-length = 160
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | \.history
  | \.local
  | buck-out
  | build
  | dist
  | migrations
  | venv
)/
'''
