name: command-storage
summary: A command line tool to store CLI commands for quick access and usage.
description: |
  cmds is a command-line tool designed to store CLI commands for quick access and usage.
version: 0.1.1
confinement: strict
grade: stable
base: core22

parts:
  python:
    plugin: python
    python-version: 3.9
    source: .
    source-type: git
    source-tag: v0.1.1
    source-depth: 1
    build-packages:
      - python3
      - python3-pip
    stage-packages:
      - python3

apps:
  cmds:
    command: usr/bin/cmds
